#
# This file is part of the chalkbars npm package. Copyright (C) 2015 and above Shogun <shogun@cowtech.it>.
# Licensed under the MIT license, which can be found at http://www.opensource.org/licenses/mit-license.php.
#

language: node_js
script: npm run-script travis-ci
node_js:
  - "5.0"
  - "5.5"
  - "5"
notifications:
  email: false
addons:
  code_climate:
    repo_token: 30dc05cfa2081d2a59ff8d7f1c0bc64b9367f8568f1991e59187405c2e325469